### ISSUE TITLE
 Error creating Gigya SDK

### ISSUE THREAD

**Issue by kidandcat** [SAP/gigya-flutter-plugin#14]
I'm getting this error when creating a release APK:

```
E/AndroidRuntime(13063): java.lang.RuntimeException: Unable to start activity ComponentInfo{es.sonypictures.reactions/es.sonypictures.reactions.MainActivity}: java.lang.RuntimeException: Error creating Gigya SDK (did you forget to Gigya.setApplication or missing apiKey?)
E/AndroidRuntime(13063):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3322)
E/AndroidRuntime(13063):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3471)
E/AndroidRuntime(13063):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime(13063):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(13063):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(13063):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058)
E/AndroidRuntime(13063):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(13063):        at android.os.Looper.loop(Looper.java:226)
E/AndroidRuntime(13063):        at android.app.ActivityThread.main(ActivityThread.java:7592)
E/AndroidRuntime(13063):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13063):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(13063):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

I've tried configuring Gigya's ApiKey using the two methods available:

https://sap.github.io/gigya-android-sdk/sdk-core/
I've configured the Gigya SDK following the instructions, and it works when running in debug mode.

**Comment by tal-mi** [comment]
Sorry for the delayed response. 
I will investigate the issue and update as soon as I can.

**Comment by kidandcat** [comment]
I don't think so, I'll check it again.

**Comment by tal-mi** [comment]
Please attach the following so I can inspect it better:
1. A detailed log/error of the release build process.
2. Release build steps (apk/bundle...).

Thanks

**Comment by kidandcat** [comment]
build.gradle:
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "es.sonypictures.reactions"
        minSdkVersion 24
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
   }

    buildTypes {
        debug {
           signingConfig signingConfigs.release
        }
        release {
           signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'android.arch.work:work-runtime:1.0.0'
    implementation project(":fluzo-sdk-2.2.0-PRO")
    implementation "androidx.core:core-ktx:+"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.gms:play-services-auth:16.0.1'
    implementation 'com.facebook.android:facebook-android-sdk:5.+'
}

```

**Comment by tal-mi** [comment]
Can you also provide detailed log of the error?

Thanks.

**Comment by kidandcat** [comment]
That was a cached build, this is a clean one:
[build.txt](https://github.com/SAP/gigya-flutter-plugin/files/7082925/build.txt)


Regarding the error, what I post in the first message is all I get. And it only happens when running the release APK or running flutter in release mode (but then I don't have any logs, it just crashes)

**Comment by tal-mi** [comment]
Please try to add the following and update me if anything changes.

buildTypes {
        debug {
           signingConfig signingConfigs.release
        }
        release {
           shrinkResources false
           minifyEnabled false
           signingConfig signingConfigs.release
        }
    }

**Comment by kidandcat** [comment]
It's working with these options.

**Comment by tal-mi** [comment]
Okay. I will investigate further to see why theses options are necessary.
Thanks you.

**Comment by kidandcat** [comment]
Is not a top priority anyway. I'm closing this issue, but it would be great to have the no shrink option in the documentation.

Thanks for the quick response!

**Comment by tal-mi** [comment]
Shrinking support is not scheduled for Q4 this year.
You can try initializing the SDK via the new initSDK feature added last version.

**Comment by KarlChow92** [comment]
Encountering same issue unfortunately.

**Comment by John-Dormevil** [comment]
This error is produce without shrinking `MissingPluginException(No implementation found for method initSdk on channel gigya_flutter_plugin)`

**Comment by pwa-tapptic** [comment]
> This error is produce without shrinking `MissingPluginException(No implementation found for method initSdk on channel gigya_flutter_plugin)`

Same here. Have you found a workaround for this?

**Comment by pwa-tapptic** [comment]
Not found it in the doc but I checked example app and I fixed the issue by adding manually two dependencies in `build.gradle`
```groovy
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
```
