### ISSUE TITLE
 MissingPluginException(No implementation found for method showScreenSet on channel gigya_flutter_plugin)

### ISSUE THREAD

**Issue by vinzaceto** [SAP/gigya-flutter-plugin#26]
HI,
I'm facing an error when I try to use an apk built in release mode.

Unhandled Exception: MissingPluginException(No implementation found for method showScreenSet on channel gigya_flutter_plugin)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154)
    <asynchronous suspension>
    #1      GigyaSdk.showScreenSet (package:gigya_flutter_plugin/gigya_flutter_plugin.dart:298)
    <asynchronous suspension>

Can you help us?
Thanks

**Comment by tal-mi** [comment]
Can you send us your code snippet or any additional information?

**Comment by arok** [comment]
Workaround https://stackoverflow.com/questions/65872226/missingpluginexception-in-flutter-in-release-mode-android

**Comment by navaronbracke** [comment]
This will probably be fixed by #68
