### ISSUE TITLE
Gigya social login error + Split mode + FireTab/AndroidTab

### ISSUE THREAD

**Issue by mukeshdiscovery** [SAP/gigya-flutter-plugin#29]
I am facing an issue while doing gigya social login.  It happens when we run the App in split mode in fireTab/AndroidTab.  We are using android sdk "gigya-android-sdk-4.0.6"

Login works fine when we run the app in single mode(No Split screen)

Error logs

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.scripps.android.foodnetwork, PID: 14777
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gigya.android.sdk.ui.WebLoginActivity}: java.lang.NullPointerException: uriString
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2934)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3075)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1824)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:211)
        at android.app.ActivityThread.main(ActivityThread.java:6740)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: uriString
        at android.net.Uri$StringUri.<init>(Uri.java:490)
        at android.net.Uri$StringUri.<init>(Uri.java:480)
        at android.net.Uri.parse(Uri.java:452)
        at com.gigya.android.sdk.ui.WebLoginActivity.onCreate(WebLoginActivity.java:72)
        at android.app.Activity.performCreate(Activity.java:7161)
        at android.app.Activity.performCreate(Activity.java:7151)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)

**Comment by tal-mi** [comment]
Please verify on later builds of the Android SDK. This does not reproduce.
