### ISSUE TITLE
Null Pointer Exception on com.gigya.android.sdk.Config.getWebViewConfig()

### ISSUE THREAD

**Issue by GiacomoRenesto** [SAP/gigya-flutter-plugin#86]
### Checklist

- [X] The issue can be reproduced in the attached sample application in the repository.
- [X] I have read the relevant [SDK documentation](https://github.com/SAP/gigya-flutter-plugin#flutter-plug-in-for-sap-customer-data-cloud) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [SAP Code of Conduct](https://github.com/SAP/gigya-flutter-plugin/blob/main/CODE_OF_CONDUCT.md).

### Description

With gigya_flutter_plugin version 1.0.7 i notice there are multiple instances of the following crash in Crashlytics console.
 **Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.gigya.android.sdk.ui.WebViewConfig com.gigya.android.sdk.Config.getWebViewConfig()' on a null object reference
       at com.gigya.android.sdk.ui.plugin.GigyaPluginFragment.setUpWebViewElement(GigyaPluginFragment.java:219)
       at com.gigya.android.sdk.ui.plugin.GigyaPluginFragment.onViewCreated(GigyaPluginFragment.java:195)**

### Reproduction

I cant find a way to reproduce this crash yet.

### SDK version

1.0.7

### Android/iOS

Android

**Comment by tal-mi** [comment]
Issue fixed in later versions of the Android SDK 7.2.+
